### ISSUE TITLE
Raspberry Pi 3 build issue

### ISSUE THREAD

**Issue by faucon2001** [aranym/aranym#9]
commit 5e1db18 doesn't build properly on a RPi 3 with Debian Jessie and SDL 1.2.15 repo version.
Aranym non JIT is 50% slower than normal (measured with Kronos and also a basic tar), phweather crash, VDI drawing is shifted left in windows and elevator size is wrong.
Aranym JIT : speed is normal, but phweather complaints that it doesn't find LDG codec, Kronos crashes, XaAESsnapshot crashes.
Both : can't build with IEEE fpu, just with UAE and MPFR.
Error Messages during make with IEEE fpu :
	In file included from natfeat/nf_objs.cpp:60:0:
	natfeat/nfjpeg.h:71:20: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
	  const int xMCUs = 16;
	natfeat/nfjpeg.h:72:20: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
	  const int yRows = 16;
	uae_cpu/fpu/fpu_ieee.cpp: In function ‘void fpuop_arithmetic(uint32, uint32)’:
	uae_cpu/fpu/fpu_ieee.cpp:1797:32: error: too few arguments to function ‘void make_inf(fpu_register&, bool)’
		 make_inf(FPU registers[reg]);
	In file included from uae_cpu/fpu/fpu_ieee.cpp:133:0:
	./uae_cpu/fpu/mathlib.h:580:26: note: declared here
	 PRIVATE inline void FFPU make_inf(fpu_register & r, bool negative)

Searching with git bisect I have found that the last good commit was 7373ac9
and the first bad a030b4c

**Comment by th-otto** [comment]
The error in fpu_ieee.cpp shoud be fixed now. Also the warning.

**Comment by faucon2001** [comment]
I confirm, IEEE fpu error and warnings have disapeared. Aranym builds now correctly. Many Thanks for this fast fix.
The other bugs remain : 50% slower non JIT, mouse trail garbage, phweather and Kronos can find LDG.

**Comment by joysfera** [comment]
Could you please find out by bisecting since when (which commit) ARAnyM is slower by 50 % on your Raspberry Pi?
Also, did you want to write "can find LDG" or is it a typo?

**Comment by faucon2001** [comment]
sorry this is a typo error : please read "can't find LDG"
commit a030b4c is the first bad one giving a 50% slower Aranym non JIT.
commit 7373ac9 was the last good one.

**Comment by th-otto** [comment]
On Donnerstag, 4. Oktober 2018 19:56:49 CEST Petr Stehlík wrote:
> Could you please find out by bisecting since when (which commit) ARAnyM is
> slower by 50 % on your Raspberry Pi? Also, did you want to write "can find
> LDG" or is it a typo?

I think the reason for the slowdown is already found, caused by choosing 
compiler options that don't work very well for that specific target.

**Comment by joysfera** [comment]
@th-otto can this be closed now if both issues were resolved?

**Comment by th-otto** [comment]
Only @faucon2001 can tell, i currently have no way to test arm versions, nor do i have any reference data for performance tests.

**Comment by faucon2001** [comment]
I haven’t gotten time so far to test the new arm version as I don’t currently have access to my equipment. I’ll report as soon as I get it back.

**Comment by ragnar76** [comment]
> Only @faucon2001 can tell, i currently have no way to test arm versions, nor do i have any reference data for performance tests.
Do you need a Raspi 3B+ for testing? I have a few lying around, i could send you one

**Comment by th-otto** [comment]
That's a nice offer, but what else would i need? And to be honest, i really would appreciate to get help in this matter from someone else, there are already so many thing to do ;)
