### PR TITLE
Fix build with glibc 2.36

### PR DESCRIPTION
**Pull request by atsampson**
Include both `<sys/time.h>` and `<time.h>` if available.

Nothing in aranym defines `TIME_WITH_SYS_TIME`, so on Linux `sysdeps.h` was only including `<sys/time.h>`. This breaks the build with glibc 2.36 since that header doesn't include the definitions of `localtime`, etc.

### CODE REVIEW

**Comment by atsampson** [comment]
It looks like `TIME_WITH_SYS_TIME` used to be defined by older versions of autoconf's `AC_HEADER_TIME` macro - the warning in #81 is related.

**Comment by th-otto** [comment]
By incidence, i changed the autoconf macros just yesterday. Could you try again with current version?

**Comment by atsampson** [comment]
Certainly. With current master (dbead3155c4ca9f26898b597438a6b2497c99136), using autoconf 2.71 and glibc 2.36 on Linux, the configure script defines `HAVE_TIME_H` and `HAVE_SYS_TIME_H`, but not `TIME_WITH_SYS_TIME`. The build then fails when compiling `hardware.cpp` and `ikbd.cpp` because `<time.h>` has never been included:

```
In file included from hardware.cpp:31:
./include/rtc.h:88:19: error: field ‘frozen_time’ has incomplete type ‘tm’
   88 |         struct tm frozen_time;
ikbd.cpp: In member function ‘virtual void IKBD::WriteData(uint8)’:
ikbd.cpp:227:62: error: ‘time’ was not declared in this scope; did you mean ‘utime’?
  227 |                                                 time_t tim = time(NULL);
```
(etc.)

**Comment by th-otto** [comment]
Ah damn, i was quite sure i had changed sysdeps.h already, but somehow that patch seems to have disappeared.
